allow using alias in path
fred104/webpack-import-glob-loader pull request #2
Opened 2019-04-15 22:08 UTC by ruifortes

loader context doesn't have access to global config now so I used the options object.

2019-06-05 10:03 UTC, fred104 requested changes
Hi Rui, thanks for your kind PR. Can you help add some tests and modify the README.md?

2019-06-05 10:03 UTC, fred104 commented on index.js
> +			Object.entries(alias).some(([alias, repl]) => {
We prefer two spaces here.

2019-06-05 10:03 UTC, fred104 commented on index.js
> +  var alias = loaderUtils.getOptions(this).alias
Missing semicolon here.

2020-09-16 15:32 UTC, soluml commented
@ruifortes, @fred104 - Ran into this issue today, would love to be able to use Alias's with this loader.  I see this is a year old issue, any chance of it being resolved? Can I help? Seems like the PR just needs some linting changes and and updated package-lock.

2020-09-17 02:11 UTC, fred104 commented
@soluml If you can help, that would be great. 👍

2020-09-25 18:17 UTC, soluml commented
@fred104, @ruifortes - Done in PR #4

2022-12-26 08:31 UTC, merged